### ISSUE TITLE
Target files not generated in the state directory

### ISSUE THREAD

**Issue by joemirizio** [dbt-labs/dbt-server#117]
The `target` directory is generated at the repository root, rather than the state directory (e.g. `./target` vs `./working-dir/state-my-proj/target`). Is this by design?

When using `/parse`, this issue causes dbt to not recognize the `partial_parse.msgpack` and forces full parsing, as indicated in the stdout message `Partial parse save file not found. Starting full parse.`. However, if the `target` directory (with the `partial_parse.msgpack`) is moved to the state directory, it WILL partial parse (this message will not appear) and the `partial_parse.msgpack` will continue to be overridden on subsequent calls.

When using `/run` the `target` directory is also generated at the root and is overridden by calls to different `state_ids`.

**Comment by lostmygithubaccount** [comment]
hello! the design of this is in flux -- @racheldaniel may have some thoughts here

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
