### ISSUE TITLE
[Feature] Add authentication for dbt-worker callback url in `tasks.py`

### ISSUE THREAD

**Issue by vladimirdinolov-8451** [dbt-labs/dbt-server#212]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We're looking at using dbt-server at scale and we've noticed that the call to the endpoint we provide doesn't enable us to add authentication. The endpoint we are providing requires a JWT. For example, the `dbt_worker` callback URL that was introduced in the latest dbt-server PRs doesn't have an option to authenticate requests.

You can find the source code for the callback URL here: [https://github.com/dbt-labs/dbt-server/blob/468c4788859f393c3dbdee73edc8f173ca2ac7e8/dbt_worker/tasks.py#L38](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbt-labs%2Fdbt-server%2Fblob%2F468c4788859f393c3dbdee73edc8f173ca2ac7e8%2Fdbt_worker%2Ftasks.py%23L38&data=05%7C01%7Cvladimir.dinolov.contractor%408451.com%7Ce9f2f2ec62eb455163ce08db36e2c67a%7C5f9dc6bdf38a454a864cc803691193c5%7C0%7C0%7C638164119833563802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ufo6rcH2q1dlLJby7fb%2BEyK7SqRiL8UVFCxId2%2FkyWA%3D&reserved=0)

We're wondering if there's a way we can add our own authentication, or if dbt has a solution for configuring authentication that hasn't been released yet.

### Describe alternatives you've considered

Adding our own authentication.

### Who will this benefit?

Any and all consumers of the dbt-server API.

### Are you interested in contributing this feature?

Possibly.

### Anything else?

See the source code here: [https://github.com/dbt-labs/dbt-server/blob/468c4788859f393c3dbdee73edc8f173ca2ac7e8/dbt_worker/tasks.py#L38](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbt-labs%2Fdbt-server%2Fblob%2F468c4788859f393c3dbdee73edc8f173ca2ac7e8%2Fdbt_worker%2Ftasks.py%23L38&data=05%7C01%7Cvladimir.dinolov.contractor%408451.com%7Ce9f2f2ec62eb455163ce08db36e2c67a%7C5f9dc6bdf38a454a864cc803691193c5%7C0%7C0%7C638164119833563802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ufo6rcH2q1dlLJby7fb%2BEyK7SqRiL8UVFCxId2%2FkyWA%3D&reserved=0)

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
