### ISSUE TITLE
[Bug][release-0.2.0 ] It's no module named 'dbt.lib' when  i installed dbt-core-1.5.0,and cound not import load_profile_project form 'dbt.lib' when i installed dbt-core-1.4.x 

### ISSUE THREAD

**Issue by liangriyu** [dbt-labs/dbt-server#236]
### Is this a new bug in dbt-server?

- [X] I believe this is a new bug in dbt-server
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

It's no module named 'dbt.lib' when  i installed dbt-core-1.5.0,and cound not import load_profile_project form 'dbt.lib' when i installed dbt-core-1.4.x ;

1. I want to confirm that only dbt-core v1.4.x can be used for dbt-server v0.2.0?
2. cound not import load_profile_project form 'dbt.lib' what shoud i do?

### Expected Behavior

successfully import dbt.lib for dbt_server/services/dbt_service.py 

### Steps To Reproduce

1. add dbt-postgres==1.4.6 to  dev-requirements.txt
2. pip install -r requirements.txt -r dev-requirements.txt --force

### Environment

```markdown
- dbt-adapter & version:
- dbt-server version:
```

**Comment by vladimirdinolov-8451** [comment]
We had this same issue and used a pre-release (at that time) version of 1.5. It was something like 1.5xx. Good luck!

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
