### ISSUE TITLE
[Feature] Add environment variable to control profiling

### ISSUE THREAD

**Issue by chrispasakarnis** [dbt-labs/dbt-server#244]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, enabling profiling is controlled by the same environment variable as APM; you are unable to enable APM without also enabling profiling. These should be controlled by two separate environment variables.

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
