### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by robcresswell** [dbt-labs/dbt-server#249]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

Hello! Sorry I couldn't find a more appropriate way to start this discussion. I've previously hopped into the dbt slack channels for a few days but it seemed overwhelmed with people asking questions and few responses, so I was hoping a slower async GitHub discussion might be easier. Please redirect me elsewhere if this is not true 😇 

What's the current plans with regards to the maintenance of this project? It has _some_ recent commits, but no prereleases that I can see for ~8 months now. There appears to be images being built, but I couldn't see where these are pushed, and my google-fu failed me. I'm really interested in using this project; I'd been building something similar already and was quite embarrassed that I didn't stumble across this sooner.

I'm keen to hear if this is still a priority, or if development focus has been shifted elsewhere. I'd love to be able to contribute with docs, feedback, or code

**Comment by jx2lee** [comment]
https://docs.getdbt.com/blog/deprecation-of-dbt-server#summary
🤤

**Comment by alittlesliceoftom** [comment]
Maybe more generally, is anyone actively using this? It seems like a useful project, but without installing a bit unclear how ready a state for usage it was left.

**Comment by marclevine-8451** [comment]
> Maybe more generally, is anyone actively using this? It seems like a useful project, but without installing a bit unclear how ready a state for usage it was left.

I use it.  It is useful, yes.  Scales well for our needs.  It took a bit to implement, it's not something you can just use out of the box.
